name: Update workshop packages
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: WebApp
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'webapp.zip'
        directory: 'src/webapp'
    
    - name: Solutions
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'solutions.zip'
        directory: 'src/solutions'

    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "*.zip"
        allowUpdates: true