name: Update workshop packages
on:
  push:
    branches:
      - main

jobs:
  update_packages:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: zip solutions
      run:  cd src/solutions && zip -r ../../solutions.zip .

    - name: zip webapp
      run:  cd src/webapp && zip -r ../../webapp.zip .

    - name: Update release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: Workshop packages
        tag: latest
        artifacts: "*.zip"
        allowUpdates: true